"use client";

/* eslint-disable @typescript-eslint/no-unused-vars */
import { useState, useMemo } from "react";
import { Search, X } from "lucide-react";

import {
  MdFamilyRestroom,
  MdPerson,
  MdChildCare,
  MdBoy,
  MdGirl,
  MdFace,
  MdFace2,
  MdFace3,
  MdFace4,
  MdFace5,
  MdFace6,
  MdWoman,
  MdMan,
  MdElderly,
  MdElderlyWoman,
  MdSportsEsports,
  MdSportsSoccer,
  MdSportsBasketball,
  MdMusicNote,
  MdStar,
  MdStarBorder,
  MdFavorite,
  MdFavoriteBorder,
  MdHome,
  MdSchool,
  MdRestaurant,
  MdLocalCafe,
  MdCake,
  MdPets,
  MdBrush,
  MdCreate,
  MdAutoStories,
  MdMenuBook,
  MdScience,
  MdCalculate,
  MdColorLens,
  MdCameraAlt,
  MdVideocam,
  MdMic,
  MdHeadphones,
  MdSmartphone,
  MdComputer,
  MdLaptop,
  MdWatch,
  MdDirectionsBike,
  MdDirectionsCar,
  MdFlight,
  MdTrain,
  MdPool,
  MdPark,
  MdBeachAccess,
  MdEmojiEmotions,
  MdCelebration,
  MdEmojiEvents,
  MdMilitaryTech,
  MdWorkspacePremium,
  MdCardGiftcard,
  MdAttachMoney,
  MdSavings,
  MdVolunteerActivism,
  MdHealthAndSafety,
  MdMedicalServices,
  MdLocalHospital,
  MdFitnessCenter,
  MdSportsGymnastics,
  MdNightlightRound,
  MdWbSunny,
  MdCloud,
  MdWaterDrop,
  MdLocalFlorist,
  MdYard,
  MdPestControl,
  MdRecycling,
  MdCleaningServices,
  MdLocalLaundryService,
  MdInventory,
  MdCheckroom,
  MdLocalGroceryStore,
  MdShoppingCart,
  MdStore,
  MdCarpenter,
  MdPlumbing,
  MdElectricBolt,
  MdConstruction,
  MdArchitecture,
  MdEngineering,
  MdBiotech,
  MdCode,
  MdPsychology,
  MdDraw,
  MdPalette,
  MdAnimation,
  MdMovie,
  MdTheaters,
  MdLiveTv,
  MdRadio,
  MdPodcasts,
  MdNewspaper,
  MdMenuBook as MdBook,
  MdEditNote,
  MdAssignment,
  MdQuiz,
  MdHive,
  MdExtension,
  MdToys,
  MdSportsMotorsports,
  MdSportsTennis,
  MdSportsGolf,
  MdSportsHockey,
  MdSportsCricket,
  MdSportsRugby,
  MdSnowboarding,
  MdSledding,
  MdSurfing,
  MdSkateboarding,
  MdHiking,
  MdDirectionsWalk,
  MdAccessibility,
  MdAccountBalance,
  MdAccountBalanceWallet,
  MdSavings as MdWallet,
} from "react-icons/md";

import {
  FaUser,
  FaUsers,
  FaChild,
  FaBaby,

  FaUserTie,
  FaUserNurse,
  FaUserGraduate,
  FaUserShield,
  FaUserSecret,
  FaUserAstronaut,
  FaSpider,
  FaDragon,
  FaHorse,
  FaDog,
  FaCat,
  FaFish,
  FaKiwiBird,
  FaFrog,
  FaBug,
  FaOtter,
  FaCrow,
  FaDove,
  FaFaucet,
  FaFire,
  FaFireAlt,
  FaSun,
  FaMoon,
  FaCloudSun,
  FaCloudMoon,
  FaCloudRain,
  FaSnowflake,
  FaWind,
  FaRainbow,
  FaStar,
  FaStarHalfAlt,
  FaHeart,
  FaHeartBroken,
  FaHandHoldingHeart,
  FaHandshake,
  FaThumbsUp,
  FaThumbsDown,
  FaSmile,
  FaSmileBeam,
  FaSmileWink,
  FaLaugh,
  FaLaughBeam,
  FaLaughSquint,
  FaSurprise,
  FaMeh,
  FaMehBlank,
  FaMehRollingEyes,
  FaFrown,
  FaFrownOpen,
  FaAngry,
  FaTired,
  FaDizzy,
  FaFlushed,
  FaGrimace,
  FaSadTear,
  FaSadCry,
  FaCouch,
  FaBed,
  FaBath,
  FaShower,
  FaUmbrellaBeach,
  FaCampground,
  FaTree,
  FaSeedling,
  FaLeaf,
  FaMountain,
  FaWater,
  FaWaveSquare,
  FaAnchor,
  FaShip,
  FaFish as FaFish2,
  FaMotorcycle,
  FaTruck,
  FaTractor,
  FaBus,
  FaPlane,
  FaPlaneArrival,
  FaPlaneDeparture,
  FaHelicopter,
  FaRocket,
  FaSpaceShuttle,
  FaSatellite,
  FaGlobeAmericas,
  FaGlobeAfrica,
  FaGlobeAsia,
  FaGlobeEurope,
  FaGlobe,
  FaMapMarkerAlt,
  FaMapPin,
  FaMapMarkedAlt,
  FaCompass,
  FaMountain as FaMountain2,
  FaArchway,
  FaBuilding,
  FaChurch,
  FaMosque,
  FaSynagogue,
  FaLandmark,
  FaMonument,
  FaCity,
  FaHouseUser,
  FaIgloo,
  FaVihara,
  FaWarehouse,
  FaHospital,
  FaSchool,
  FaUniversity,
  FaStore as FaStore2,
  FaCoffee,
  FaUtensils,
  FaPizzaSlice,
  FaHotdog,
  FaIceCream,
  FaCandyCane,
  FaCookie,
  FaCookieBite,
  FaLemon,
  FaAppleAlt,
  FaCarrot,
  FaBreadSlice,
  FaEgg,
  FaDrumstickBite,
  FaBacon,
  FaPepperHot,
  FaCheese,
  FaWineBottle,
  FaWineGlass,
  FaBeer,
  FaCocktail,
  FaBabyCarriage,
  FaFootballBall,
  FaBasketballBall,
  FaBaseballBall,
  FaVolleyballBall,
  FaBowlingBall,
  FaGolfBall,
  FaHockeyPuck,
  FaSkiing,
  FaSkiingNordic,
  FaSnowboarding as FaSnowboard,
  FaSwimmer,
  FaDumbbell,
  FaRunning,
  FaWalking,
  FaHiking as FaHiking2,
  FaChess,
  FaPuzzlePiece,
  FaGamepad,
  FaHeadphones,
  FaGuitar,
  FaDrum,
  FaKeyboard,
  FaMicrophone,
  FaMicrophoneAlt,
  FaCompactDisc,
  FaRecordVinyl,
  FaMusic,
  FaPodcast,
  FaTv,
  FaFilm,
  FaCamera,
  FaVideo,
  FaImage,
  FaPaintBrush,
  FaPalette,
  FaPencilAlt,
  FaPen,
  FaMarker,
  FaHighlighter,
  FaEraser,
  FaRuler,
  FaCut,
  FaPaperclip,
  FaStickyNote,
  FaBook,
  FaBookOpen,
  FaBookReader,
  FaBookmark,
  FaGraduationCap,
  FaUserMd,
  FaStethoscope,
  FaMedkit,
  FaPrescription,
  FaDna,
  FaMicroscope,
  FaBrain,
  FaLungs,
  FaHeartbeat,
  FaBandAid,
  FaTooth,
  FaEye,
  FaXRay,
  FaSyringe,
  FaHospital as FaHospital2,
  FaAmbulance,
  FaNotesMedical,
  FaHandHoldingMedical,
  FaUserNurse as FaNurse,
  FaToolbox,
  FaHardHat,
  FaCogs,
  FaCog,
  FaWrench,
  FaScrewdriver,
  FaHammer,
  FaKey,
  FaLock,
  FaUnlock,
  FaShieldAlt,
  FaExclamationTriangle,
  FaExclamationCircle,
  FaInfoCircle,
  FaCheckCircle,
  FaTimesCircle,
  FaQuestionCircle,
  FaLightbulb,
  FaBolt,
  FaTachometerAlt,
  FaChartBar,
  FaChartLine,
  FaChartPie,
  FaChartArea,
  FaClipboard,
  FaClipboardCheck,
  FaClipboardList,
  FaFileAlt,
  FaFileInvoice,
  FaFileContract,
  FaFolder,
  FaFolderOpen,
  FaEnvelope,
  FaEnvelopeOpen,
  FaMailBulk,
  FaAt,
  FaHashtag,
  FaPercent,
  FaDollarSign,
  FaEuroSign,
  FaPoundSign,
  FaMoneyBillWave,
  FaCreditCard,
  FaWallet,
  FaPiggyBank,
  FaReceipt,
  FaShoppingBag,
  FaShoppingCart as FaCart,
  FaStore as FaStore3,
  FaCashRegister,
  FaGift,
  FaGifts,
  FaBirthdayCake,
  FaCalendarAlt,
  FaCalendarDay,
  FaCalendarWeek,
  FaCalendarCheck,
  FaClock,
  FaStopwatch,
  FaHourglassHalf,
  FaHourglassStart,
  FaHourglassEnd,
  FaBell,
  FaBellSlash,
  FaBullhorn,
  FaShareAlt,
  FaShare,
  FaLink,
  FaUnlink,
  FaQrcode,
  FaBarcode,
  FaTag,
  FaTags,
  FaThumbtack,
  FaMap,
  FaGlobe as FaGlobe2,
  FaSatelliteDish,
  FaWifi,
  FaSignal,
  FaBroadcastTower,
  FaSimCard,
  FaMemory,
  FaMicrochip,
  FaServer,
  FaDatabase,
  FaCloud as FaCloud2,
  FaCloudUploadAlt,
  FaCloudDownloadAlt,
  FaCloudSun as FaCloudSun2,
  FaDownload,
  FaUpload,
  FaSyncAlt,
  FaRedo,
  FaUndo,
  FaHistory,
  FaSearch,
  FaSearchPlus,
  FaSearchMinus,
  FaFilter,
  FaSort,
  FaSortAmountUp,
  FaSortAmountDown,
  FaArrowsAlt,
  FaArrowsAltH,
  FaArrowsAltV,
  FaExpand,
  FaCompress,
  FaExternalLinkAlt,
  FaSignInAlt,
  FaSignOutAlt,
  FaUserPlus,
  FaUserMinus,
  FaUserCheck,
  FaUserTimes,
  FaUsersCog,
  FaUsersSlash,
  FaPowerOff,
  FaCog as FaSettings,
  FaSlidersH,
  FaPaintRoller,
  FaSwatchbook,
  FaTape,
  FaMagic,
  FaAsterisk,
  FaEllipsisH,
  FaEllipsisV,
  FaBars,
  FaTh,
  FaThLarge,
  FaThList,
  FaList,
  FaListUl,
  FaListOl,
  FaTable,
  FaBorderAll,
  FaBorderNone,
} from "react-icons/fa";

import {
  HiUser,
  HiUsers,
  HiUserGroup,
  HiUserCircle,
  HiUserAdd,
  HiUserRemove,
  HiHome,
  HiHeart,
  HiStar,
  HiLightningBolt,
  HiSparkles,
  HiAcademicCap,
  HiAdjustments,
  HiAnnotation,
  HiArchive,
  HiArrowCircleDown,
  HiArrowCircleLeft,
  HiArrowCircleRight,
  HiArrowCircleUp,
  HiBadgeCheck,
  HiBell,
  HiBookOpen,
  HiCalendar,
  HiCamera,
  HiChatAlt,
  HiCheck,
  HiCheckCircle,
  HiChevronDown,
  HiChevronLeft,
  HiChevronRight,
  HiChevronUp,
  HiClipboard,
  HiClock,
  HiCog,
  HiCollection,
  HiColorSwatch,
  HiCube,
  HiCurrencyDollar,
  HiDatabase,
  HiDesktopComputer,
  HiDeviceMobile,
  HiDocument,
  HiDocumentText,
  HiDownload,
  HiDuplicate,
  HiEmojiHappy,
  HiExclamation,
  HiExclamationCircle,
  HiEye,
  HiEyeOff,
  HiFilter,
  HiFingerPrint,
  HiFlag,
  HiFolder,
  HiFolderOpen,
  HiGlobe,
  HiGlobeAlt,
  HiHashtag,
  HiHeart as HiHeart2,
  HiHome as HiHome2,
  HiInformationCircle,
  HiKey,
  HiLibrary,
  HiLightBulb,
  HiLightningBolt as HiBolt,
  HiLink,
  HiLocationMarker,
  HiLockClosed,
  HiLockOpen,
  HiLogin,
  HiLogout,
  HiMail,
  HiMailOpen,
  HiMap,
  HiMenu,
  HiMicrophone,
  HiMinus,
  HiMoon,
  HiMusicNote,
  HiNewspaper,
  HiOfficeBuilding,
  HiOutlineAcademicCap,
  HiOutlineCog,
  HiOutlineUserGroup,
  HiPencil,
  HiPhone,
  HiPhotograph,
  HiPlus,
  HiPlusCircle,
  HiPrinter,
  HiPuzzle,
  HiQuestionMarkCircle,
  HiReceiptRefund,
  HiRefresh,
  HiReply,
  HiSearch,
  HiSelector,
  HiServer,
  HiShare,
  HiShieldCheck,
  HiShoppingBag,
  HiShoppingCart,
  HiSortAscending,
  HiSortDescending,
  HiSpeakerphone,
  HiStar as HiStar2,
  HiTable,
  HiTag,
  HiTemplate,
  HiTerminal,
  HiThumbUp,
  HiTrendingUp,
  HiTruck,
  HiUpload,
  HiUserGroup as HiGroup2,
  HiViewGrid,
  HiViewList,
  HiVolumeUp,
  HiX,
  HiXCircle,
  HiAnnotation as HiChat,
  HiCake,
  HiBadgeCheck as HiAward,
  HiSparkles as HiSparkle,
} from "react-icons/hi";

import {
  IoPerson,
  IoPeople,
  IoPersonAdd,
  IoPersonRemove,
  IoWoman,
  IoMan,
  IoHome,
  IoHeart,
  IoStar,
  IoStarOutline,
  IoSunny,
  IoMoon,
  IoCloudy,
  IoRainy,
  IoSnow,
  IoThunderstorm,
  IoFlame,
  IoWater,
  IoLeaf,
  IoFlower,
  IoGlobe,
  IoGlobeOutline,
  IoMusicalNote,
  IoMusicalNotes,
  IoCamera,
  IoVideocam,
  IoImage,
  IoImages,
  IoFilm,
  IoGameController,
  IoTrophy,
  IoGift,
  IoGiftOutline,
  IoBalloon,
  IoColorPalette,
  IoBrush,
  IoCreate,
  IoPencil,
  IoTrash,
  IoTrashOutline,
  IoClose,
  IoCheckmark,
  IoCheckmarkCircle,
  IoAlertCircle,
  IoInformationCircle,
  IoWarning,
  IoHelpCircle,
  IoSearch,
  IoSettings,
  IoOptions,
  IoList,
  IoGrid,
  IoMenu,
  IoEllipsisHorizontal,
  IoEllipsisVertical,
  IoAdd,
  IoRemove,
  IoArrowUp,
  IoArrowDown,
  IoArrowBack,
  IoArrowForward,
  IoRefresh,
  IoSync,
  IoDownload,
  IoLink,
  IoUnlink,
  IoCopy,
  IoDocuments,
  IoDocument,
  IoFolder,
  IoFolderOpen,
  IoMail,
  IoMailOpen,
  IoChatbox,
  IoChatbubble,
  IoCall,
  IoPhonePortrait,
  IoLaptop,
  IoDesktop,
  IoWatch,
  IoFitness,
  IoFootball,
  IoBasketball,
  IoPricetag,
  IoPricetags,
  IoCart,
  IoBag,
  IoStorefront,
  IoWallet,
  IoCash,
  IoCard,
  IoTime,
  IoCalendar as IoCal,
  IoAlarm,
  IoStopwatch,
  IoTimer,
  IoLocation,
  IoMap,
  IoCompass,
  IoFlag,
  IoNavigate,
  IoRocket,
  IoAirplane,
  IoBoat,
  IoCar,
  IoBicycle,
  IoBus,
  IoTrain,
  IoSubway,
  IoKey,
  IoLockClosed as IoLock,
  IoLockOpen as IoUnlock,
  IoShield,
  IoShieldCheckmark,
  IoBuild,
  IoConstruct,
  IoHammer,
  IoExtensionPuzzle,
  IoColorWand,
  IoSparkles,
  IoFitness as IoExercise,
  IoFastFood,
  IoPizza,
  IoIceCream as IoIce,
  IoCafe,
  IoWine,
  IoBeer,
  IoNutrition,
  IoMedical,
  IoHeart as IoMedicalHeart,
  IoPulse,
  IoBody,
  IoSkull,
  IoSkullOutline,
  IoAccessibility,
  IoEye,
  IoEyeOff as IoEyeOff,
  IoEar,
  IoHandLeft,
  IoHandRight,
  IoThumbsUp,
  IoThumbsDown,
  IoFingerPrint,
  IoBody as IoPersonBody,
} from "react-icons/io5";

import {
  TbUser,
  TbUsers,
  TbHome,
  TbHeart,
  TbStar,
  TbStarHalf,
  TbMoon,
  TbSun,
  TbCloud,
  TbSnowflake,
  TbFlame,
  TbDroplet,
  TbLeaf,
  TbPlant,
  TbTree,
  TbFlower,
  TbGlobe,
  TbMusic,
  TbCamera,
  TbVideo,
  TbDeviceGamepad,
  TbTrophy,
  TbGift,
  TbBalloon,
  TbPalette,
  TbBrush,
  TbPencil,
  TbEraser,
  TbCut,
  TbCopy,
  TbClipboard,
  TbFile,
  TbFileText,
  TbFolder,
  TbMail,
  TbMessage,
  TbPhone,
  TbDeviceMobile,
  TbDeviceLaptop,
  TbDeviceDesktop,
  TbSearch,
  TbSettings,
  TbAdjustments,
  TbFilter,
  TbSortAscending,
  TbGridDots,
  TbLayoutList,
  TbMenu,
  TbDots,
  TbPlus,
  TbMinus,
  TbCheck,
  TbX,
  TbAlertTriangle,
  TbAlertCircle,
  TbInfoCircle,
  TbQuestionMark,
  TbRefresh,
  TbDownload,
  TbUpload,
  TbLink,
  TbUnlink,
  TbTrash,
  TbEdit,
  TbShare,
  TbLock,
  TbLockOpen,
  TbKey,
  TbShield,
  TbShieldCheck,
  TbClock,
  TbCalendar,
  TbAlarm,
  TbMap,
  TbMapPin,
  TbCompass,
  TbFlag,
  TbRocket,
  TbPlane,
  TbCar,
  TbBus,
  TbTrain,
  TbShip,
  TbWalk,
  TbRun,
  TbSwimming,
  TbWalk as TbHiking2,
  TbDumbbell,
  TbSoccerField,
  TbBallBasketball,
  TbGolf,
  TbBowling,
  TbChessKing,
  TbPuzzle,
  TbBuilding,
  TbBuildingSkyscraper,
  TbBuildingChurch,
  TbTent,
  TbCampfire,
  TbWorld,
  TbPlane as TbAirplane,
  TbAnchor,
  TbFish,
  TbBug,
  TbDog,
  TbCat,
  TbFeather,
  TbHorse,
  TbButterfly,
  TbPaw,
  TbEgg,
  TbCheese,
  TbApple,
  TbLemon,
  TbCarrot,
  TbBread,
  TbMug,
  TbBeer,
  TbChefHat,
  TbCake,
  TbCandy,
  TbCookie,
  TbIceCream,
  TbTool,
  TbHammer,
  TbKey as TbKey2,
  TbLock as TbLock2,
  TbCoin,
  TbWallet,
  TbCreditCard,
  TbShoppingBag,
  TbShoppingCart,
  TbReceipt,
  TbDiscount,
  TbTag,
  TbTags,
  TbGift as TbGift2,
  TbBell,
  TbBulb,
  TbCandle,
  TbPower,
  TbBattery,
  TbBolt,
  TbPlug,
  TbMath,
  TbMathFunction,
  TbCalculator,
  TbChartBar,
  TbChartLine,
  TbChartPie,
  TbChartArea,
  TbBrain,
  TbAtom,
  TbDna,
  TbMicroscope,
  TbStethoscope,
  TbMedicineSyrup,
  TbBandage,
  TbPill,
  TbVaccine,
  TbNurse,
  TbWheelchair,
} from "react-icons/tb";

export type IconEntry = {
  id: string;
  label: string;
  icon: React.ReactNode;
  tags: string[];
};

type LibraryTab = {
  id: string;
  label: string;
  icons: IconEntry[];
};

function buildLibraries(): LibraryTab[] {
  const mdIcons: IconEntry[] = [
    { id: "md-family", label: "عائلة", icon: <MdFamilyRestroom />, tags: ["family", "عائلة"] },
    { id: "md-person", label: "شخص", icon: <MdPerson />, tags: ["person", "شخص"] },
    { id: "md-child", label: "طفل", icon: <MdChildCare />, tags: ["child", "طفل"] },
    { id: "md-boy", label: "ولد", icon: <MdBoy />, tags: ["boy", "ولد"] },
    { id: "md-girl", label: "بنت", icon: <MdGirl />, tags: ["girl", "بنت"] },
    { id: "md-face", label: "وجه", icon: <MdFace />, tags: ["face", "وجه"] },
    { id: "md-face2", label: "وجه 2", icon: <MdFace2 />, tags: ["face"] },
    { id: "md-face3", label: "وجه 3", icon: <MdFace3 />, tags: ["face"] },
    { id: "md-face4", label: "وجه 4", icon: <MdFace4 />, tags: ["face"] },
    { id: "md-face5", label: "وجه 5", icon: <MdFace5 />, tags: ["face"] },
    { id: "md-face6", label: "وجه 6", icon: <MdFace6 />, tags: ["face"] },
    { id: "md-woman", label: "امرأة", icon: <MdWoman />, tags: ["woman", "امرأة"] },
    { id: "md-man", label: "رجل", icon: <MdMan />, tags: ["man", "رجل"] },
    { id: "md-elderly", label: "كبير", icon: <MdElderly />, tags: ["elderly", "كبير"] },
    { id: "md-elderly-woman", label: " كبيرة", icon: <MdElderlyWoman />, tags: ["elderly", " كبيرة"] },
    { id: "md-sports", label: "رياضة", icon: <MdSportsEsports />, tags: ["sports", "رياضة", "ألعاب"] },
    { id: "md-soccer", label: "كرة قدم", icon: <MdSportsSoccer />, tags: ["soccer", "كرة"] },
    { id: "md-basketball", label: "كرة سلة", icon: <MdSportsBasketball />, tags: ["basketball", "كرة"] },
    { id: "md-music", label: "موسيقى", icon: <MdMusicNote />, tags: ["music", "موسيقى"] },
    { id: "md-star", label: "نجمة", icon: <MdStar />, tags: ["star", "نجمة"] },
    { id: "md-favorite", label: "قلب", icon: <MdFavorite />, tags: ["heart", "قلب", "حب"] },
    { id: "md-home", label: "بيت", icon: <MdHome />, tags: ["home", "بيت"] },
    { id: "md-school", label: "مدرسة", icon: <MdSchool />, tags: ["school", "مدرسة"] },
    { id: "md-restaurant", label: "مطعم", icon: <MdRestaurant />, tags: ["restaurant", "مطعم", "أكل"] },
    { id: "md-cafe", label: "قهوة", icon: <MdLocalCafe />, tags: ["cafe", "قهوة"] },
    { id: "md-cake", label: "كعكة", icon: <MdCake />, tags: ["cake", "عيد ميلاد"] },
    { id: "md-pets", label: "حيوان", icon: <MdPets />, tags: ["pets", "حيوان"] },
    { id: "md-brush", label: "فرشة", icon: <MdBrush />, tags: ["brush", "رسم"] },
    { id: "md-create", label: "قلم", icon: <MdCreate />, tags: ["pen", "قلم"] },
    { id: "md-book", label: "كتاب", icon: <MdAutoStories />, tags: ["book", "كتاب"] },
    { id: "md-science", label: "علوم", icon: <MdScience />, tags: ["science", "علوم"] },
    { id: "md-calculator", label: "آلة حاسبة", icon: <MdCalculate />, tags: ["calculator", "حساب"] },
    { id: "md-palette", label: "لوحة ألوان", icon: <MdColorLens />, tags: ["palette", "ألوان"] },
    { id: "md-camera", label: "كاميرا", icon: <MdCameraAlt />, tags: ["camera", "كاميرا"] },
    { id: "md-video", label: "فيديو", icon: <MdVideocam />, tags: ["video", "فيديو"] },
    { id: "md-mic", label: "ميكروفون", icon: <MdMic />, tags: ["mic", "صوت"] },
    { id: "md-headphones", label: "سماعات", icon: <MdHeadphones />, tags: ["headphones", "سماعات"] },
    { id: "md-phone", label: "هاتف", icon: <MdSmartphone />, tags: ["phone", "هاتف"] },
    { id: "md-computer", label: "كمبيوتر", icon: <MdComputer />, tags: ["computer", "كمبيوتر"] },
    { id: "md-bike", label: "دراجة", icon: <MdDirectionsBike />, tags: ["bike", "دراجة"] },
    { id: "md-car", label: "سيارة", icon: <MdDirectionsCar />, tags: ["car", "سيارة"] },
    { id: "md-flight", label: "طائرة", icon: <MdFlight />, tags: ["flight", "طائرة"] },
    { id: "md-pool", label: "مسبح", icon: <MdPool />, tags: ["pool", "سباحة"] },
    { id: "md-park", label: "حديقة", icon: <MdPark />, tags: ["park", "حديقة"] },
    { id: "md-beach", label: "شاطئ", icon: <MdBeachAccess />, tags: ["beach", "شاطئ"] },
    { id: "md-emoji", label: "ابتسامة", icon: <MdEmojiEmotions />, tags: ["emoji", "ابتسامة"] },
    { id: "md-celebrate", label: "احتفال", icon: <MdCelebration />, tags: ["celebrate", "احتفال"] },
    { id: "md-trophy", label: "كأس", icon: <MdEmojiEvents />, tags: ["trophy", "كأس"] },
    { id: "md-medal", label: "ميدالية", icon: <MdMilitaryTech />, tags: ["medal", "ميدالية"] },
    { id: "md-premium", label: "مميّز", icon: <MdWorkspacePremium />, tags: ["premium", "مميز"] },
    { id: "md-gift", label: "هدية", icon: <MdCardGiftcard />, tags: ["gift", "هدية"] },
    { id: "md-health", label: "صحة", icon: <MdHealthAndSafety />, tags: ["health", "صحة"] },
    { id: "md-fitness", label: "لياقة", icon: <MdFitnessCenter />, tags: ["fitness", "رياضة"] },
    { id: "md-night", label: "ليل", icon: <MdNightlightRound />, tags: ["night", "ليل"] },
    { id: "md-sun", label: "شمس", icon: <MdWbSunny />, tags: ["sun", "شمس"] },
    { id: "md-cloud", label: "سحابة", icon: <MdCloud />, tags: ["cloud", "سحابة"] },
    { id: "md-water", label: "ماء", icon: <MdWaterDrop />, tags: ["water", "ماء"] },
    { id: "md-flower", label: "زهرة", icon: <MdLocalFlorist />, tags: ["flower", "زهرة"] },
    { id: "md-recycle", label: "إعادة تدوير", icon: <MdRecycling />, tags: ["recycle", "إعادة"] },
    { id: "md-clean", label: "تنظيف", icon: <MdCleaningServices />, tags: ["clean", "تنظيف"] },
    { id: "md-code", label: "كود", icon: <MdCode />, tags: ["code", "برمجة"] },
    { id: "md-psychology", label: "علم نفس", icon: <MdPsychology />, tags: ["psychology", "علم"] },
    { id: "md-animation", label: "رسوم متحركة", icon: <MdAnimation />, tags: ["animation", "رسوم"] },
    { id: "md-movie", label: "فيلم", icon: <MdMovie />, tags: ["movie", "فيلم"] },
    { id: "md-quiz", label: "اختبار", icon: <MdQuiz />, tags: ["quiz", "اختبار"] },
    { id: "md-toys", label: "ألعاب", icon: <MdToys />, tags: ["toys", "ألعاب"] },
    { id: "md-extension", label: "إضافة", icon: <MdExtension />, tags: ["extension", "إضافة"] },
    { id: "md-hiking", label: "مشي", icon: <MdHiking />, tags: ["hiking", "مشي"] },
    { id: "md-wallet", label: "محفظة", icon: <MdSavings />, tags: ["wallet", "محفظة"] },
  ];

  const faIcons: IconEntry[] = [
    { id: "fa-user", label: "شخص", icon: <FaUser />, tags: ["user", "شخص"] },
    { id: "fa-users", label: "مجموعة", icon: <FaUsers />, tags: ["users", "مجموعة"] },
    { id: "fa-child", label: "طفل", icon: <FaChild />, tags: ["child", "طفل"] },
    { id: "fa-baby", label: "رضيع", icon: <FaBaby />, tags: ["baby", "رضيع"] },
    { id: "fa-user-tie", label: "رجل أعمال", icon: <FaUserTie />, tags: ["business", "رجل"] },
    { id: "fa-user-graduate", label: "خريج", icon: <FaUserGraduate />, tags: ["graduate", "طالب"] },
    { id: "fa-user-astronaut", label: "رائد فضاء", icon: <FaUserAstronaut />, tags: ["astronaut", "فضاء"] },
    { id: "fa-dog", label: "كلب", icon: <FaDog />, tags: ["dog", "كلب"] },
    { id: "fa-cat", label: "قطة", icon: <FaCat />, tags: ["cat", "قطة"] },
    { id: "fa-fish", label: "سمكة", icon: <FaFish />, tags: ["fish", "سمكة"] },
    { id: "fa-bird", label: "طائر", icon: <FaKiwiBird />, tags: ["bird", "طائر"] },
    { id: "fa-frog", label: "ضفدع", icon: <FaFrog />, tags: ["frog", "ضفدع"] },
    { id: "fa-horse", label: "حصان", icon: <FaHorse />, tags: ["horse", "حصان"] },
    { id: "fa-fire", label: "نار", icon: <FaFire />, tags: ["fire", "نار"] },
    { id: "fa-sun", label: "شمس", icon: <FaSun />, tags: ["sun", "شمس"] },
    { id: "fa-moon", label: "قمر", icon: <FaMoon />, tags: ["moon", "قمر"] },
    { id: "fa-snowflake", label: "ثلج", icon: <FaSnowflake />, tags: ["snow", "ثلج"] },
    { id: "fa-star", label: "نجمة", icon: <FaStar />, tags: ["star", "نجمة"] },
    { id: "fa-heart", label: "قلب", icon: <FaHeart />, tags: ["heart", "قلب"] },
    { id: "fa-thumbs-up", label: "أعجبني", icon: <FaThumbsUp />, tags: ["like", "أعجبني"] },
    { id: "fa-smile", label: "ابتسامة", icon: <FaSmile />, tags: ["smile", "ابتسامة"] },
    { id: "fa-laugh", label: "ضحك", icon: <FaLaugh />, tags: ["laugh", "ضحك"] },
    { id: "fa-cool", label: "رائع", icon: <FaSmileWink />, tags: ["cool", "رائع"] },
    { id: "fa-bed", label: "سرير", icon: <FaBed />, tags: ["bed", "نوم"] },
    { id: "fa-tree", label: "شجرة", icon: <FaTree />, tags: ["tree", "شجرة"] },
    { id: "fa-leaf", label: "ورقة", icon: <FaLeaf />, tags: ["leaf", "ورقة"] },
    { id: "fa-mountain", label: "جبل", icon: <FaMountain />, tags: ["mountain", "جبل"] },
    { id: "fa-water", label: "ماء", icon: <FaWater />, tags: ["water", "ماء"] },
    { id: "fa-anchor", label: "مرساة", icon: <FaAnchor />, tags: ["anchor", "مرساة"] },
    { id: "fa-motorcycle", label: "دراجة نارية", icon: <FaMotorcycle />, tags: ["motorcycle", "دراجة"] },
    { id: "fa-plane", label: "طائرة", icon: <FaPlane />, tags: ["plane", "طائرة"] },
    { id: "fa-rocket", label: "صاروخ", icon: <FaRocket />, tags: ["rocket", "صاروخ"] },
    { id: "fa-globe", label: "كرة أرضية", icon: <FaGlobe />, tags: ["globe", "عالم"] },
    { id: "fa-utensils", label: "أكل", icon: <FaUtensils />, tags: ["food", "أكل"] },
    { id: "fa-pizza", label: "بيتزا", icon: <FaPizzaSlice />, tags: ["pizza", "بيتزا"] },
    { id: "fa-ice-cream", label: "آيس كريم", icon: <FaIceCream />, tags: ["ice cream", "آيس كريم"] },
    { id: "fa-coffee", label: "قهوة", icon: <FaCoffee />, tags: ["coffee", "قهوة"] },
    { id: "fa-birthday-cake", label: "كعكة عيد ميلاد", icon: <FaBirthdayCake />, tags: ["birthday", "عيد ميلاد"] },
    { id: "fa-cookie", label: "كوكيز", icon: <FaCookie />, tags: ["cookie", "كوكيز"] },
    { id: "fa-football", label: "كرة أمريكية", icon: <FaFootballBall />, tags: ["football", "كرة"] },
    { id: "fa-basketball", label: "كرة سلة", icon: <FaBasketballBall />, tags: ["basketball", "كرة"] },
    { id: "fa-puzzle", label: "لغز", icon: <FaPuzzlePiece />, tags: ["puzzle", "لغز"] },
    { id: "fa-gamepad", label: "يد تحكم", icon: <FaGamepad />, tags: ["gamepad", "ألعاب"] },
    { id: "fa-guitar", label: "جيتار", icon: <FaGuitar />, tags: ["guitar", "جيتار"] },
    { id: "fa-drum", label: "طبل", icon: <FaDrum />, tags: ["drum", "طبل"] },
    { id: "fa-music", label: "موسيقى", icon: <FaMusic />, tags: ["music", "موسيقى"] },
    { id: "fa-camera", label: "كاميرا", icon: <FaCamera />, tags: ["camera", "كاميرا"] },
    { id: "fa-film", label: "فيلم", icon: <FaFilm />, tags: ["film", "فيلم"] },
    { id: "fa-paintbrush", label: "فرشة رسم", icon: <FaPaintBrush />, tags: ["paint", "رسم"] },
    { id: "fa-palette", label: "لوحة ألوان", icon: <FaPalette />, tags: ["palette", "ألوان"] },
    { id: "fa-book", label: "كتاب", icon: <FaBook />, tags: ["book", "كتاب"] },
    { id: "fa-graduation-cap", label: "تخرّج", icon: <FaGraduationCap />, tags: ["graduation", "تخرج"] },
    { id: "fa-stethoscope", label: "سماعة طبيب", icon: <FaStethoscope />, tags: ["doctor", "طبيب"] },
    { id: "fa-medkit", label: "حقيبة طوارئ", icon: <FaMedkit />, tags: ["medkit", "إسعاف"] },
    { id: "fa-dna", label: "DNA", icon: <FaDna />, tags: ["dna", "علم"] },
    { id: "fa-brain", label: "دماغ", icon: <FaBrain />, tags: ["brain", "دماغ"] },
    { id: "fa-heartbeat", label: "نبض", icon: <FaHeartbeat />, tags: ["heartbeat", "نبض"] },
    { id: "fa-cog", label: "إعدادات", icon: <FaCog />, tags: ["settings", "إعدادات"] },
    { id: "fa-wrench", label: "مفتاح ربط", icon: <FaWrench />, tags: ["wrench", "أداة"] },
    { id: "fa-hammer", label: "مطرقة", icon: <FaHammer />, tags: ["hammer", "مطرقة"] },
    { id: "fa-key", label: "مفتاح", icon: <FaKey />, tags: ["key", "مفتاح"] },
    { id: "fa-lock", label: "قفل", icon: <FaLock />, tags: ["lock", "قفل"] },
    { id: "fa-shield", label: "درع", icon: <FaShieldAlt />, tags: ["shield", "حماية"] },
    { id: "fa-lightbulb", label: "لمبة", icon: <FaLightbulb />, tags: ["lightbulb", "فكرة"] },
    { id: "fa-bolt", label: "برق", icon: <FaBolt />, tags: ["bolt", "برق"] },
    { id: "fa-chart-bar", label: "رسم بياني", icon: <FaChartBar />, tags: ["chart", "رسم بياني"] },
    { id: "fa-gift", label: "هدية", icon: <FaGift />, tags: ["gift", "هدية"] },
    { id: "fa-bell", label: "جرس", icon: <FaBell />, tags: ["bell", "تنبيه"] },
    { id: "fa-clock", label: "ساعة", icon: <FaClock />, tags: ["clock", "وقت"] },
    { id: "fa-calendar", label: "تقويم", icon: <FaCalendarAlt />, tags: ["calendar", "تقويم"] },
    { id: "fa-wallet", label: "محفظة", icon: <FaWallet />, tags: ["wallet", "محفظة"] },
    { id: "fa-piggy-bank", label: "خنزير نقود", icon: <FaPiggyBank />, tags: ["piggy", "ادخار"] },
    { id: "fa-shopping-cart", label: "سلة تسوق", icon: <FaCart />, tags: ["cart", "تسوق"] },
    { id: "fa-tag", label: "وسم", icon: <FaTag />, tags: ["tag", "وسم"] },
    { id: "fa-tent", label: "خيمة", icon: <FaCampground />, tags: ["tent", "مخيم"] },
    { id: "fa-hiking", label: "مشي", icon: <FaHiking2 />, tags: ["hiking", "مشي"] },
    { id: "fa-swimmer", label: "سباحة", icon: <FaSwimmer />, tags: ["swim", "سباحة"] },
    { id: "fa-dumbbell", label: "دمبل", icon: <FaDumbbell />, tags: ["dumbbell", "رياضة"] },
    { id: "fa-running", label: "جري", icon: <FaRunning />, tags: ["running", "جري"] },
    { id: "fa-chess", label: "شطرنج", icon: <FaChess />, tags: ["chess", "شطرنج"] },
  ];

  const hiIcons: IconEntry[] = [
    { id: "hi-user", label: "شخص", icon: <HiUser />, tags: ["user", "شخص"] },
    { id: "hi-users", label: "مجموعة", icon: <HiUsers />, tags: ["users", "مجموعة"] },
    { id: "hi-user-group", label: "مجموعة أشخاص", icon: <HiUserGroup />, tags: ["group", "مجموعة"] },
    { id: "hi-home", label: "بيت", icon: <HiHome />, tags: ["home", "بيت"] },
    { id: "hi-heart", label: "قلب", icon: <HiHeart />, tags: ["heart", "قلب"] },
    { id: "hi-star", label: "نجمة", icon: <HiStar />, tags: ["star", "نجمة"] },
    { id: "hi-lightning", label: "برق", icon: <HiLightningBolt />, tags: ["lightning", "برق"] },
    { id: "hi-sparkles", label: "بريق", icon: <HiSparkles />, tags: ["sparkles", "بريق"] },
    { id: "hi-academic", label: "تعليم", icon: <HiAcademicCap />, tags: ["academic", "تعليم"] },
    { id: "hi-bell", label: "جرس", icon: <HiBell />, tags: ["bell", "تنبيه"] },
    { id: "hi-book-open", label: "كتاب مفتوح", icon: <HiBookOpen />, tags: ["book", "كتاب"] },
    { id: "hi-calendar", label: "تقويم", icon: <HiCalendar />, tags: ["calendar", "تقويم"] },
    { id: "hi-camera", label: "كاميرا", icon: <HiCamera />, tags: ["camera", "كاميرا"] },
    { id: "hi-check", label: "تحقق", icon: <HiCheck />, tags: ["check", " صح"] },
    { id: "hi-check-circle", label: "دوائر صح", icon: <HiCheckCircle />, tags: ["check", " صح"] },
    { id: "hi-clock", label: "ساعة", icon: <HiClock />, tags: ["clock", "وقت"] },
    { id: "hi-cog", label: "إعدادات", icon: <HiCog />, tags: ["settings", "إعدادات"] },
    { id: "hi-color-swatch", label: "ألوان", icon: <HiColorSwatch />, tags: ["color", "ألوان"] },
    { id: "hi-cube", label: "مكعب", icon: <HiCube />, tags: ["cube", "مكعب"] },
    { id: "hi-currency-dollar", label: "دولار", icon: <HiCurrencyDollar />, tags: ["dollar", "فلوس"] },
    { id: "hi-database", label: "قاعدة بيانات", icon: <HiDatabase />, tags: ["database", "بيانات"] },
    { id: "hi-desktop", label: "شاشة", icon: <HiDesktopComputer />, tags: ["desktop", "شاشة"] },
    { id: "hi-document", label: "مستند", icon: <HiDocument />, tags: ["document", "مستند"] },
    { id: "hi-download", label: "تحميل", icon: <HiDownload />, tags: ["download", "تحميل"] },
    { id: "hi-emoji-happy", label: "وجه سعيد", icon: <HiEmojiHappy />, tags: ["happy", "سعيد"] },
    { id: "hi-finger-print", label: "بصمة", icon: <HiFingerPrint />, tags: ["fingerprint", "بصمة"] },
    { id: "hi-flag", label: "علم", icon: <HiFlag />, tags: ["flag", "علم"] },
    { id: "hi-globe", label: "كرة أرضية", icon: <HiGlobe />, tags: ["globe", "عالم"] },
    { id: "hi-key", label: "مفتاح", icon: <HiKey />, tags: ["key", "مفتاح"] },
    { id: "hi-light-bulb", label: "لمبة", icon: <HiLightBulb />, tags: ["bulb", "فكرة"] },
    { id: "hi-location", label: "موقع", icon: <HiLocationMarker />, tags: ["location", "موقع"] },
    { id: "hi-lock-closed", label: "مقفل", icon: <HiLockClosed />, tags: ["lock", "قفل"] },
    { id: "hi-music", label: "موسيقى", icon: <HiMusicNote />, tags: ["music", "موسيقى"] },
    { id: "hi-phone", label: "هاتف", icon: <HiPhone />, tags: ["phone", "هاتف"] },
    { id: "hi-plus-circle", label: "إضافة", icon: <HiPlusCircle />, tags: ["add", "إضافة"] },
    { id: "hi-puzzle", label: "لغز", icon: <HiPuzzle />, tags: ["puzzle", "لغز"] },
    { id: "hi-search", label: "بحث", icon: <HiSearch />, tags: ["search", "بحث"] },
    { id: "hi-shopping-bag", label: "حقيبة تسوق", icon: <HiShoppingBag />, tags: ["bag", "تسوق"] },
    { id: "hi-thumb-up", label: "أعجبني", icon: <HiThumbUp />, tags: ["like", "أعجبني"] },
    { id: "hi-trending", label: "تصاعد", icon: <HiTrendingUp />, tags: ["trending", "تصاعد"] },
    { id: "hi-truck", label: "شاحنة", icon: <HiTruck />, tags: ["truck", "شاحنة"] },
    { id: "hi-upload", label: "رفع", icon: <HiUpload />, tags: ["upload", "رفع"] },
    { id: "hi-view-grid", label: "شبكة", icon: <HiViewGrid />, tags: ["grid", "شبكة"] },
    { id: "hi-award", label: "جوائز", icon: <HiAward />, tags: ["award", "جوائز"] },
    { id: "hi-cake", label: "كعكة", icon: <HiCake />, tags: ["cake", "كعكة"] },
    { id: "hi-chat", label: "محادثة", icon: <HiChat />, tags: ["chat", "محادثة"] },
    { id: "hi-sparkle", label: "بريق", icon: <HiSparkle />, tags: ["sparkle", "بريق"] },
  ];

  const ioIcons: IconEntry[] = [
    { id: "io-person", label: "شخص", icon: <IoPerson />, tags: ["person", "شخص"] },
    { id: "io-people", label: "أشخاص", icon: <IoPeople />, tags: ["people", "أشخاص"] },
    { id: "io-woman", label: "امرأة", icon: <IoWoman />, tags: ["woman", "امرأة"] },
    { id: "io-man", label: "رجل", icon: <IoMan />, tags: ["man", "رجل"] },
    { id: "io-home", label: "بيت", icon: <IoHome />, tags: ["home", "بيت"] },
    { id: "io-heart", label: "قلب", icon: <IoHeart />, tags: ["heart", "قلب"] },
    { id: "io-star", label: "نجمة", icon: <IoStar />, tags: ["star", "نجمة"] },
    { id: "io-sunny", label: "شمس", icon: <IoSunny />, tags: ["sun", "شمس"] },
    { id: "io-moon", label: "قمر", icon: <IoMoon />, tags: ["moon", "قمر"] },
    { id: "io-flame", label: "لهب", icon: <IoFlame />, tags: ["flame", "نار"] },
    { id: "io-water", label: "ماء", icon: <IoWater />, tags: ["water", "ماء"] },
    { id: "io-leaf", label: "ورقة", icon: <IoLeaf />, tags: ["leaf", "ورقة"] },
    { id: "io-flower", label: "زهرة", icon: <IoFlower />, tags: ["flower", "زهرة"] },
    { id: "io-globe", label: "عالم", icon: <IoGlobe />, tags: ["globe", "عالم"] },
    { id: "io-music", label: "موسيقى", icon: <IoMusicalNote />, tags: ["music", "موسيقى"] },
    { id: "io-camera", label: "كاميرا", icon: <IoCamera />, tags: ["camera", "كاميرا"] },
    { id: "io-image", label: "صورة", icon: <IoImage />, tags: ["image", "صورة"] },
    { id: "io-film", label: "فيلم", icon: <IoFilm />, tags: ["film", "فيلم"] },
    { id: "io-game-controller", label: "يد تحكم", icon: <IoGameController />, tags: ["game", "ألعاب"] },
    { id: "io-trophy", label: "كأس", icon: <IoTrophy />, tags: ["trophy", "كأس"] },
    { id: "io-gift", label: "هدية", icon: <IoGift />, tags: ["gift", "هدية"] },
    { id: "io-balloon", label: "بالون", icon: <IoBalloon />, tags: ["balloon", "بالون"] },
    { id: "io-palette", label: "ألوان", icon: <IoColorPalette />, tags: ["palette", "ألوان"] },
    { id: "io-brush", label: "فرشة", icon: <IoBrush />, tags: ["brush", "رسم"] },
    { id: "io-puzzle", label: "لغز", icon: <IoExtensionPuzzle />, tags: ["puzzle", "لغز"] },
    { id: "io-sparkles", label: "بريق", icon: <IoSparkles />, tags: ["sparkles", "بريق"] },
    { id: "io-fitness", label: "لياقة", icon: <IoFitness />, tags: ["fitness", "رياضة"] },
    { id: "io-fast-food", label: "وجبة سريعة", icon: <IoFastFood />, tags: ["food", "أكل"] },
    { id: "io-pizza", label: "بيتزا", icon: <IoPizza />, tags: ["pizza", "بيتزا"] },
    { id: "io-ice-cream", label: "آيس كريم", icon: <IoIce />, tags: ["ice cream", "آيس كريم"] },
    { id: "io-cafe", label: "قهوة", icon: <IoCafe />, tags: ["cafe", "قهوة"] },
    { id: "io-medical", label: "طبي", icon: <IoMedical />, tags: ["medical", "طبي"] },
    { id: "io-thumbs-up", label: "أعجبني", icon: <IoThumbsUp />, tags: ["like", "أعجبني"] },
    { id: "io-eye", label: "عين", icon: <IoEye />, tags: ["eye", "عين"] },
    { id: "io-rocket", label: "صاروخ", icon: <IoRocket />, tags: ["rocket", "صاروخ"] },
    { id: "io-car", label: "سيارة", icon: <IoCar />, tags: ["car", "سيارة"] },
    { id: "io-bicycle", label: "دراجة", icon: <IoBicycle />, tags: ["bike", "دراجة"] },
    { id: "io-airplane", label: "طائرة", icon: <IoAirplane />, tags: ["plane", "طائرة"] },
    { id: "io-boat", label: "قارب", icon: <IoBoat />, tags: ["boat", "قارب"] },
    { id: "io-wallet", label: "محفظة", icon: <IoWallet />, tags: ["wallet", "محفظة"] },
    { id: "io-cart", label: "سلة", icon: <IoCart />, tags: ["cart", "سلة"] },
    { id: "io-bag", label: "حقيبة", icon: <IoBag />, tags: ["bag", "حقيبة"] },
    { id: "io-shield", label: "درع", icon: <IoShield />, tags: ["shield", "حماية"] },
  ];

  const tbIcons: IconEntry[] = [
    { id: "tb-user", label: "شخص", icon: <TbUser />, tags: ["user", "شخص"] },
    { id: "tb-users", label: "مجموعة", icon: <TbUsers />, tags: ["users", "مجموعة"] },
    { id: "tb-home", label: "بيت", icon: <TbHome />, tags: ["home", "بيت"] },
    { id: "tb-heart", label: "قلب", icon: <TbHeart />, tags: ["heart", "قلب"] },
    { id: "tb-star", label: "نجمة", icon: <TbStar />, tags: ["star", "نجمة"] },
    { id: "tb-moon", label: "قمر", icon: <TbMoon />, tags: ["moon", "قمر"] },
    { id: "tb-sun", label: "شمس", icon: <TbSun />, tags: ["sun", "شمس"] },
    { id: "tb-cloud", label: "سحابة", icon: <TbCloud />, tags: ["cloud", "سحابة"] },
    { id: "tb-snowflake", label: "ثلج", icon: <TbSnowflake />, tags: ["snow", "ثلج"] },
    { id: "tb-flame", label: "لهب", icon: <TbFlame />, tags: ["flame", "نار"] },
    { id: "tb-droplet", label: "قطرة", icon: <TbDroplet />, tags: ["water", "ماء"] },
    { id: "tb-leaf", label: "ورقة", icon: <TbLeaf />, tags: ["leaf", "ورقة"] },
    { id: "tb-plant", label: "نبات", icon: <TbPlant />, tags: ["plant", "نبات"] },
    { id: "tb-tree", label: "شجرة", icon: <TbTree />, tags: ["tree", "شجرة"] },
    { id: "tb-flower", label: "زهرة", icon: <TbFlower />, tags: ["flower", "زهرة"] },
    { id: "tb-globe", label: "عالم", icon: <TbGlobe />, tags: ["globe", "عالم"] },
    { id: "tb-music", label: "موسيقى", icon: <TbMusic />, tags: ["music", "موسيقى"] },
    { id: "tb-camera", label: "كاميرا", icon: <TbCamera />, tags: ["camera", "كاميرا"] },
    { id: "tb-video", label: "فيديو", icon: <TbVideo />, tags: ["video", "فيديو"] },
    { id: "tb-gamepad", label: "ألعاب", icon: <TbDeviceGamepad />, tags: ["game", "ألعاب"] },
    { id: "tb-trophy", label: "كأس", icon: <TbTrophy />, tags: ["trophy", "كأس"] },
    { id: "tb-gift", label: "هدية", icon: <TbGift />, tags: ["gift", "هدية"] },
    { id: "tb-palette", label: "ألوان", icon: <TbPalette />, tags: ["palette", "ألوان"] },
    { id: "tb-brush", label: "فرشة", icon: <TbBrush />, tags: ["brush", "رسم"] },
    { id: "tb-pencil", label: "قلم", icon: <TbPencil />, tags: ["pencil", "قلم"] },
    { id: "tb-book", label: "كتاب", icon: <TbFileText />, tags: ["book", "كتاب"] },
    { id: "tb-puzzle", label: "لغز", icon: <TbPuzzle />, tags: ["puzzle", "لغز"] },
    { id: "tb-building", label: "مبنى", icon: <TbBuilding />, tags: ["building", "مبنى"] },
    { id: "tb-tent", label: "خيمة", icon: <TbTent />, tags: ["tent", "خيمة"] },
    { id: "tb-campfire", label: "نار مخيم", icon: <TbCampfire />, tags: ["campfire", "مخيم"] },
    { id: "tb-rocket", label: "صاروخ", icon: <TbRocket />, tags: ["rocket", "صاروخ"] },
    { id: "tb-anchor", label: "مرساة", icon: <TbAnchor />, tags: ["anchor", "مرساة"] },
    { id: "tb-fish", label: "سمكة", icon: <TbFish />, tags: ["fish", "سمكة"] },
    { id: "tb-dog", label: "كلب", icon: <TbDog />, tags: ["dog", "كلب"] },
    { id: "tb-cat", label: "قطة", icon: <TbCat />, tags: ["cat", "قطة"] },
    { id: "tb-bird", label: "طائر", icon: <TbFeather />, tags: ["bird", "طائر"] },
    { id: "tb-horse", label: "حصان", icon: <TbHorse />, tags: ["horse", "حصان"] },
    { id: "tb-butterfly", label: "فراشة", icon: <TbButterfly />, tags: ["butterfly", "فراشة"] },
    { id: "tb-bug", label: "حشرة", icon: <TbBug />, tags: ["bug", "حشرة"] },
    { id: "tb-paw", label: "بصمة حيوان", icon: <TbPaw />, tags: ["paw", "حيوان"] },
    { id: "tb-dumbbell", label: "دمبل", icon: <TbDumbbell />, tags: ["dumbbell", "رياضة"] },
    { id: "tb-swimming", label: "سباحة", icon: <TbSwimming />, tags: ["swim", "سباحة"] },
    { id: "tb-hiking", label: "مشي", icon: <TbHiking2 />, tags: ["hiking", "مشي"] },
    { id: "tb-soccer", label: "كرة قدم", icon: <TbSoccerField />, tags: ["soccer", "كرة"] },
    { id: "tb-basketball", label: "كرة سلة", icon: <TbBallBasketball />, tags: ["basketball", "كرة"] },
    { id: "tb-chess", label: "شطرنج", icon: <TbChessKing />, tags: ["chess", "شطرنج"] },
    { id: "tb-bell", label: "جرس", icon: <TbBell />, tags: ["bell", "تنبيه"] },
    { id: "tb-bulb", label: "لمبة", icon: <TbBulb />, tags: ["bulb", "فكرة"] },
    { id: "tb-brain", label: "دماغ", icon: <TbBrain />, tags: ["brain", "دماغ"] },
    { id: "tb-wallet", label: "محفظة", icon: <TbWallet />, tags: ["wallet", "محفظة"] },
    { id: "tb-gift", label: "هدية", icon: <TbGift2 />, tags: ["gift", "هدية"] },
  ];

  return [
    { id: "material", label: "Material", icons: mdIcons },
    { id: "fontawesome", label: "Font Awesome", icons: faIcons },
    { id: "heroicons", label: "Heroicons", icons: hiIcons },
    { id: "ionicons", label: "Ionicons", icons: ioIcons },
    { id: "tabler", label: "Tabler", icons: tbIcons },
  ];
}

export default function IconPicker({
  value,
  onChange,
  onClose,
}: {
  value: string;
  onChange: (id: string) => void;
  onClose: () => void;
}) {
  const [search, setSearch] = useState("");
  const [activeLib, setActiveLib] = useState("material");
  const libraries = useMemo(() => buildLibraries(), []);

  const currentLib = libraries.find((l) => l.id === activeLib) || libraries[0];

  const filteredIcons = useMemo(() => {
    if (!search.trim()) return currentLib.icons;
    const q = search.toLowerCase();
    return currentLib.icons.filter(
      (icon) =>
        icon.label.includes(q) ||
        icon.tags.some((t) => t.toLowerCase().includes(q))
    );
  }, [currentLib, search]);

  return (
    <div className="fixed inset-0 z-[100] bg-black/50 flex items-center justify-center p-4">
      <div className="bg-white rounded-2xl w-full max-w-2xl max-h-[80vh] flex flex-col shadow-2xl">
        <div className="flex items-center justify-between p-4 border-b border-zinc-200">
          <h3 className="font-bold text-lg text-zinc-900">اختر أيقونة</h3>
          <button
            onClick={onClose}
            className="p-1 hover:bg-zinc-100 rounded-lg transition-colors"
          >
            <X className="w-5 h-5 text-zinc-500" />
          </button>
        </div>

        <div className="p-3 border-b border-zinc-100">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-zinc-400" />
            <input
              type="text"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="بحث عن أيقونة..."
              className="w-full pl-9 pr-4 py-2.5 border border-zinc-200 rounded-xl text-sm text-right focus:ring-2 focus:ring-[var(--primary)] focus:border-[var(--primary)] outline-none"
            />
          </div>
        </div>

        <div className="flex gap-1 p-2 border-b border-zinc-100 overflow-x-auto">
          {libraries.map((lib) => (
            <button
              key={lib.id}
              onClick={() => setActiveLib(lib.id)}
              className={`px-3 py-1.5 rounded-lg text-xs font-medium whitespace-nowrap transition-colors ${
                activeLib === lib.id
                  ? "text-white"
                  : "bg-zinc-100 text-zinc-600 hover:bg-zinc-200"
              }`}
              style={
                activeLib === lib.id
                  ? { backgroundColor: "var(--primary)" }
                  : undefined
              }
            >
              {lib.label} ({lib.icons.length})
            </button>
          ))}
        </div>

        <div className="flex-1 overflow-y-auto p-4">
          <div className="grid grid-cols-6 sm:grid-cols-8 gap-2">
            {filteredIcons.map((icon) => (
              <button
                key={icon.id}
                onClick={() => {
                  onChange(icon.id);
                  onClose();
                }}
                className={`flex flex-col items-center gap-1 p-2 rounded-xl border-2 transition-all hover:scale-105 ${
                  value === icon.id
                    ? "border-[var(--primary)] bg-[var(--primary)]/10"
                    : "border-transparent hover:border-zinc-200 hover:bg-zinc-50"
                }`}
                title={icon.label}
              >
                <span className="text-2xl">{icon.icon}</span>
                <span className="text-[9px] text-zinc-500 truncate w-full text-center">
                  {icon.label}
                </span>
              </button>
            ))}
          </div>
          {filteredIcons.length === 0 && (
            <p className="text-center text-zinc-400 py-8">
              لا توجد نتائج
            </p>
          )}
        </div>
      </div>
    </div>
  );
}
